### ISSUE TITLE
Can't connect to WS server via WSL 2

### ISSUE THREAD

**Issue by aniljaiswal** [webextension-toolbox/webpack-webextension-plugin#97] opened 2021-04-28 06:58 UTC
I'm running the extension from WSL2 Ubuntu on windows 10. I just can't seem to get the auto-reloading to work because of the connectivity issue. Everything else works fine.. my APIs which are also inside WSL2 connect perfectly fine via localhost.

![Screenshot 2021-04-28 122620](https://user-images.githubusercontent.com/43805107/116359875-f0f3eb00-a81c-11eb-9ae0-ad5824a8d20a.png)

I also tried the server host to `0.0.0.0` but it changed nothing.

Any help is appreciated.

**Comment by balcsida** [comment] 2021-06-27 17:04
Hi @aniljaiswal,

This is caused by WSL2 using DNS entry to resolve the IP address of `localhost`.
It will be fixed in the next release.

Kind regards,
@balcsida

**Closed** 2021-06-27 17:09 UTC
